### ISSUE TITLE
Include `frint-props` and `frint-props-react`

### ISSUE THREAD

**Issue by fahad19** [frintjs/frint.js.org#12]
Include both the packages in docs sidebar.

**Comment by maryam-saeidi** [comment]
@fahad19 Where are the documentation of these packages? And in which section of the sidebar should the package names be included?

**Comment by fahad19** [comment]
Can be found in these places:

* https://github.com/frintjs/frint-props/tree/master/packages/frint-props
* https://github.com/frintjs/frint-props/tree/master/packages/frint-props-react

The links can go under Sidebar (under "PACKAGES" heading).
